// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright 2018 Appvia Ltd All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePrincipalsOKCode is the HTTP code returned for type DeletePrincipalsOK
const DeletePrincipalsOKCode int = 200

/*DeletePrincipalsOK Deletion successful

swagger:response deletePrincipalsOK
*/
type DeletePrincipalsOK struct {
}

// NewDeletePrincipalsOK creates DeletePrincipalsOK with default headers values
func NewDeletePrincipalsOK() *DeletePrincipalsOK {

	return &DeletePrincipalsOK{}
}

// WriteResponse to the client
func (o *DeletePrincipalsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
