// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright 2018 Appvia Ltd All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/anchore-rbac/models"
)

// GetDomainsOKCode is the HTTP code returned for type GetDomainsOK
const GetDomainsOKCode int = 200

/*GetDomainsOK Domain name listing

swagger:response getDomainsOK
*/
type GetDomainsOK struct {

	/*
	  In: Body
	*/
	Payload models.DomainList `json:"body,omitempty"`
}

// NewGetDomainsOK creates GetDomainsOK with default headers values
func NewGetDomainsOK() *GetDomainsOK {

	return &GetDomainsOK{}
}

// WithPayload adds the payload to the get domains o k response
func (o *GetDomainsOK) WithPayload(payload models.DomainList) *GetDomainsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get domains o k response
func (o *GetDomainsOK) SetPayload(payload models.DomainList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDomainsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DomainList, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
