// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright 2018 Appvia Ltd All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/anchore-rbac/models"
)

// GetPrincipalsOKCode is the HTTP code returned for type GetPrincipalsOK
const GetPrincipalsOKCode int = 200

/*GetPrincipalsOK Domain name listing

swagger:response getPrincipalsOK
*/
type GetPrincipalsOK struct {

	/*
	  In: Body
	*/
	Payload models.PrincipalList `json:"body,omitempty"`
}

// NewGetPrincipalsOK creates GetPrincipalsOK with default headers values
func NewGetPrincipalsOK() *GetPrincipalsOK {

	return &GetPrincipalsOK{}
}

// WithPayload adds the payload to the get principals o k response
func (o *GetPrincipalsOK) WithPayload(payload models.PrincipalList) *GetPrincipalsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get principals o k response
func (o *GetPrincipalsOK) SetPayload(payload models.PrincipalList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPrincipalsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PrincipalList, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
