// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright 2018 Appvia Ltd All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/anchore-rbac/models"
)

// PostAuthorizeOKCode is the HTTP code returned for type PostAuthorizeOK
const PostAuthorizeOKCode int = 200

/*PostAuthorizeOK authorized

swagger:response postAuthorizeOK
*/
type PostAuthorizeOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthorizationDecision `json:"body,omitempty"`
}

// NewPostAuthorizeOK creates PostAuthorizeOK with default headers values
func NewPostAuthorizeOK() *PostAuthorizeOK {

	return &PostAuthorizeOK{}
}

// WithPayload adds the payload to the post authorize o k response
func (o *PostAuthorizeOK) WithPayload(payload *models.AuthorizationDecision) *PostAuthorizeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post authorize o k response
func (o *PostAuthorizeOK) SetPayload(payload *models.AuthorizationDecision) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthorizeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
