// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright 2018 Appvia Ltd All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Anchore Engine Authorization Plugin API. This is expected to be run securely (e.g. same host with no external connectivity",
    "title": "Authorization Plugin API",
    "contact": {
      "email": "dev@anchore.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.1.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/authorize": {
      "post": {
        "description": "Authorize a principal against a set of actions",
        "parameters": [
          {
            "name": "authz_request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AuthorizationRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "authorized",
            "schema": {
              "$ref": "#/definitions/AuthorizationDecision"
            }
          }
        }
      }
    },
    "/domains": {
      "get": {
        "description": "List known domains, if applicable",
        "responses": {
          "200": {
            "description": "Domain name listing",
            "schema": {
              "$ref": "#/definitions/DomainList"
            }
          }
        }
      },
      "post": {
        "description": "Create a new domain, if applicable, in the authz system",
        "parameters": [
          {
            "name": "domain",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Domain"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Domain init succeeded"
          }
        }
      },
      "delete": {
        "description": "Delete information about a domain, if applicable",
        "parameters": [
          {
            "name": "domain",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Domain"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deletion successful"
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "A healthcheck to call to verify availability. Returns 200 ok",
        "responses": {
          "200": {
            "description": "Ok healthy"
          }
        }
      }
    },
    "/principals": {
      "get": {
        "description": "List known domains, if applicable",
        "responses": {
          "200": {
            "description": "Domain name listing",
            "schema": {
              "$ref": "#/definitions/PrincipalList"
            }
          }
        }
      },
      "post": {
        "description": "Create a new principal, if applicable, in the authz system",
        "parameters": [
          {
            "name": "principal",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Principal"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Principal init succeeded"
          }
        }
      },
      "delete": {
        "description": "Delete information about a principal, if applicable",
        "parameters": [
          {
            "name": "principal",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Principal"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deletion successful"
          }
        }
      }
    }
  },
  "definitions": {
    "Action": {
      "description": "An action to be authorized",
      "type": "object",
      "required": [
        "domain",
        "action",
        "target"
      ],
      "properties": {
        "action": {
          "type": "string"
        },
        "domain": {
          "description": "The domain for the action and target, typically this is the Anchore Account",
          "type": "string"
        },
        "target": {
          "type": "string"
        }
      }
    },
    "ActionSet": {
      "description": "A list of actions",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Action"
      }
    },
    "AuthorizationDecision": {
      "description": "The result of an authorization evaluation",
      "type": "object",
      "required": [
        "principal",
        "allowed",
        "denied",
        "ttl"
      ],
      "properties": {
        "allowed": {
          "$ref": "#/definitions/ActionSet"
        },
        "denied": {
          "$ref": "#/definitions/ActionSet"
        },
        "principal": {
          "$ref": "#/definitions/Principal"
        },
        "ttl": {
          "description": "An optional ttl for the result. If provided the caller should respect it.",
          "type": "integer"
        }
      }
    },
    "AuthorizationRequest": {
      "description": "The input for an authorization decision",
      "type": "object",
      "required": [
        "principal",
        "actions"
      ],
      "properties": {
        "actions": {
          "$ref": "#/definitions/ActionSet"
        },
        "principal": {
          "$ref": "#/definitions/Principal"
        }
      }
    },
    "Domain": {
      "description": "The name of a domain",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "The name of the domain",
          "type": "string"
        }
      }
    },
    "DomainList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Domain"
      }
    },
    "Principal": {
      "description": "The name of a domain",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "The name of the principal",
          "type": "string"
        }
      }
    },
    "PrincipalList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Principal"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Anchore Engine Authorization Plugin API. This is expected to be run securely (e.g. same host with no external connectivity",
    "title": "Authorization Plugin API",
    "contact": {
      "email": "dev@anchore.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.1.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/authorize": {
      "post": {
        "description": "Authorize a principal against a set of actions",
        "parameters": [
          {
            "name": "authz_request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AuthorizationRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "authorized",
            "schema": {
              "$ref": "#/definitions/AuthorizationDecision"
            }
          }
        }
      }
    },
    "/domains": {
      "get": {
        "description": "List known domains, if applicable",
        "responses": {
          "200": {
            "description": "Domain name listing",
            "schema": {
              "$ref": "#/definitions/DomainList"
            }
          }
        }
      },
      "post": {
        "description": "Create a new domain, if applicable, in the authz system",
        "parameters": [
          {
            "name": "domain",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Domain"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Domain init succeeded"
          }
        }
      },
      "delete": {
        "description": "Delete information about a domain, if applicable",
        "parameters": [
          {
            "name": "domain",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Domain"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deletion successful"
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "A healthcheck to call to verify availability. Returns 200 ok",
        "responses": {
          "200": {
            "description": "Ok healthy"
          }
        }
      }
    },
    "/principals": {
      "get": {
        "description": "List known domains, if applicable",
        "responses": {
          "200": {
            "description": "Domain name listing",
            "schema": {
              "$ref": "#/definitions/PrincipalList"
            }
          }
        }
      },
      "post": {
        "description": "Create a new principal, if applicable, in the authz system",
        "parameters": [
          {
            "name": "principal",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Principal"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Principal init succeeded"
          }
        }
      },
      "delete": {
        "description": "Delete information about a principal, if applicable",
        "parameters": [
          {
            "name": "principal",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Principal"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deletion successful"
          }
        }
      }
    }
  },
  "definitions": {
    "Action": {
      "description": "An action to be authorized",
      "type": "object",
      "required": [
        "domain",
        "action",
        "target"
      ],
      "properties": {
        "action": {
          "type": "string"
        },
        "domain": {
          "description": "The domain for the action and target, typically this is the Anchore Account",
          "type": "string"
        },
        "target": {
          "type": "string"
        }
      }
    },
    "ActionSet": {
      "description": "A list of actions",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Action"
      }
    },
    "AuthorizationDecision": {
      "description": "The result of an authorization evaluation",
      "type": "object",
      "required": [
        "principal",
        "allowed",
        "denied",
        "ttl"
      ],
      "properties": {
        "allowed": {
          "$ref": "#/definitions/ActionSet"
        },
        "denied": {
          "$ref": "#/definitions/ActionSet"
        },
        "principal": {
          "$ref": "#/definitions/Principal"
        },
        "ttl": {
          "description": "An optional ttl for the result. If provided the caller should respect it.",
          "type": "integer"
        }
      }
    },
    "AuthorizationRequest": {
      "description": "The input for an authorization decision",
      "type": "object",
      "required": [
        "principal",
        "actions"
      ],
      "properties": {
        "actions": {
          "$ref": "#/definitions/ActionSet"
        },
        "principal": {
          "$ref": "#/definitions/Principal"
        }
      }
    },
    "Domain": {
      "description": "The name of a domain",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "The name of the domain",
          "type": "string"
        }
      }
    },
    "DomainList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Domain"
      }
    },
    "Principal": {
      "description": "The name of a domain",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "The name of the principal",
          "type": "string"
        }
      }
    },
    "PrincipalList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Principal"
      }
    }
  }
}`))
}
